/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Control.Cfuncionario;
import Model.Mfuncionario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALFREDO CACONDA
 */
public class funcionario extends javax.swing.JFrame {

    /**
     * Creates new form entrada
     */
    public funcionario() {
        initComponents();
        pesquisar("");
        txtnome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnsalvar = new rojeru_san.RSButton();
        txtnome = new rojeru_san.RSMTextFull();
        cbgenero = new javax.swing.JComboBox();
        txtbi = new rojeru_san.RSMTextFull();
        txttelefone = new rojeru_san.RSMTextFull();
        cbestado = new javax.swing.JComboBox();
        txtespecialidade = new rojeru_san.RSMTextFull();
        txtsenha = new rojeru_san.RSMPassView();
        cbcargo = new javax.swing.JComboBox();
        txtemail = new rojeru_san.RSMTextFull();
        txtcontrato = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpesquisar = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbfuncionario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel6.setBackground(new java.awt.Color(51, 204, 255));

        btnsalvar.setBackground(new java.awt.Color(255, 102, 0));
        btnsalvar.setText("GUARDAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        txtnome.setPlaceholder("NOME ");
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        cbgenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbgenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONAR O GENERO", "MASCULINO", "FEMENINO" }));
        cbgenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbgeneroKeyPressed(evt);
            }
        });

        txtbi.setPlaceholder("Nº DO BI");
        txtbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbiKeyPressed(evt);
            }
        });

        txttelefone.setPlaceholder("TELEFONE");
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        txttelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefoneKeyPressed(evt);
            }
        });

        cbestado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR O ESTADO", "ACTIVO", "NÃO ACTIVO" }));
        cbestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbestadoKeyPressed(evt);
            }
        });

        txtespecialidade.setPlaceholder("ESPECIALIDADE");
        txtespecialidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtespecialidadeKeyPressed(evt);
            }
        });

        txtsenha.setPlaceholder("SENHA");
        txtsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsenhaKeyPressed(evt);
            }
        });

        cbcargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbcargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR O CARGO", "GERENTE", "FUNCIONÁRIO", "TECNICO" }));
        cbcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbcargoKeyPressed(evt);
            }
        });

        txtemail.setPlaceholder("EMAIL");
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });

        try {
            txtcontrato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcontrato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcontrato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcontrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcontratoMouseClicked(evt);
            }
        });
        txtcontrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontratoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA DO CONTRATO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtcontrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(cbcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtespecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtespecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        txtpesquisar.setPlaceholder("Pesquisar");
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        tbfuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbfuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbfuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbfuncionario);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTO DE FUNCIONÁRIO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VOLTAR");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int id = 0, codigo;
    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void tbfuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbfuncionarioMouseClicked

        codigo = (int) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 0);
        //codigo para o duplo clique
        if (evt.getClickCount() == 2) {
            //codigo do Joptiona 
            //declaramos uma vetor objecto que vai armazenar os itens selecionado
            Object[] recebe = {"EDITAR", "CANCELAR"};
            int valor = (int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, recebe, recebe[1]);

            if (valor == 0) {
                
                txtnome.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 1));
                cbgenero.setSelectedItem((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 2));
                txtespecialidade.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 3));
                txtbi.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 4));
                txttelefone.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 5));
                txtcontrato.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 6));
                cbestado.setSelectedItem((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 7));
                txtemail.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 8));
                txtsenha.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 9));
                cbcargo.setSelectedItem((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 10));
                btnsalvar.setText("ACTUALIZAR");
                id++;
            }

        }
    }//GEN-LAST:event_tbfuncionarioMouseClicked

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        if (id == 0) {
            salvar();
        } else {
            atualizar();
            btnsalvar.setText("ATUALIZAR");
        }
        pesquisar("");
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Curso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            cbgenero.requestFocus();
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void cbgeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbgeneroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtbi.requestFocus();
        }
    }//GEN-LAST:event_cbgeneroKeyPressed

    private void txtbiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txttelefone.requestFocus();
        }
    }//GEN-LAST:event_txtbiKeyPressed

    private void txttelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            cbestado.requestFocus();
        }
    }//GEN-LAST:event_txttelefoneKeyPressed

    private void cbestadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbestadoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            cbcargo.requestFocus();
        }
    }//GEN-LAST:event_cbestadoKeyPressed

    private void cbcargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbcargoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtespecialidade.requestFocus();
        }
    }//GEN-LAST:event_cbcargoKeyPressed

    private void txtespecialidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtespecialidadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtsenha.requestFocus();
        }
    }//GEN-LAST:event_txtespecialidadeKeyPressed

    private void txtsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            salvar();
            pesquisar("");
        }
    }//GEN-LAST:event_txtsenhaKeyPressed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtcontratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontratoMouseClicked
        //txtcontrato.setText(buscardata());
    }//GEN-LAST:event_txtcontratoMouseClicked

    private void txtcontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnsalvar;
    private javax.swing.JComboBox cbcargo;
    private javax.swing.JComboBox cbestado;
    private javax.swing.JComboBox cbgenero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbfuncionario;
    private rojeru_san.RSMTextFull txtbi;
    private javax.swing.JFormattedTextField txtcontrato;
    private rojeru_san.RSMTextFull txtemail;
    private rojeru_san.RSMTextFull txtespecialidade;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtpesquisar;
    private rojeru_san.RSMPassView txtsenha;
    private rojeru_san.RSMTextFull txttelefone;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        Mfuncionario f = new Mfuncionario();
        Cfuncionario c = new Cfuncionario();
        String nome = txtnome.getText();
        String especialidade = txtespecialidade.getText();
        String genero = (String) cbgenero.getSelectedItem();
        String senha = txtsenha.getText();
        String bi = txtbi.getText();
        String data_contrato = txtcontrato.getText();
        String email = txtemail.getText();
        String estado = (String) cbestado.getSelectedItem();
        String cargo = (String) cbcargo.getSelectedItem();
        String telefone = txttelefone.getText();
        if (!nome.isEmpty() && !senha.isEmpty() && !telefone.isEmpty()
                && !estado.isEmpty() && !cargo.isEmpty() && !especialidade.isEmpty()
                && !bi.isEmpty() && !genero.isEmpty()) {
            f.setCargo(cargo);
            f.setData_contrato(data_contrato);
            f.setEmail(email);
            f.setTelefone(telefone);
            f.setEspecialidade(especialidade);
            f.setGenero(genero);
            f.setN_bi(bi);
            f.setNome(nome);
            f.setSenha(senha);
            f.setStatu(estado);
            c.salvar(f);
        } else {
            f.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        }
        LIMPAR();
    }

    private void atualizar() {
        Mfuncionario f = new Mfuncionario();
        Cfuncionario c = new Cfuncionario();

        if (txtbi.getText().equals("") || cbcargo.getSelectedIndex() == 0
                || txtnome.getText().equals("") || txtsenha.getText().equals("") || txttelefone.getText().equals("")
                || txtespecialidade.getText().equals("") || cbestado.getSelectedIndex() == 0
                || cbgenero.getSelectedIndex() == 0) {
            f.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        } else {
            String nome = txtnome.getText();
            String especialidade = txtespecialidade.getText();
            String genero = (String) cbgenero.getSelectedItem();
            String senha = txtsenha.getText();
            String bi = txtbi.getText();
            String data_contrato = txtcontrato.getText();
            String email = txtemail.getText();
            String estado = (String) cbestado.getSelectedItem();
            String cargo = (String) cbcargo.getSelectedItem();
            String telefone = txttelefone.getText();
            f.setCargo(cargo);
            f.setData_contrato(data_contrato);
            f.setEmail(email);
            f.setTelefone(telefone);
            f.setEspecialidade(especialidade);
            f.setGenero(genero);
            f.setN_bi(bi);
            f.setNome(nome);
            f.setSenha(senha);
            f.setStatu(estado);
            f.setId_funcionario(codigo);
            c.actualizar(f);
        }
        LIMPAR();
    }

    public int pesquisar(String pesquisar) {
        int qtdfuncionario = 0;
        Cfuncionario f = new Cfuncionario();
        DefaultTableModel dt = (DefaultTableModel) tbfuncionario.getModel();
        Object[] recebe = {"CODIGO", "NOME", "GENERO", "ESPECIALIDADE", "Nº DO BI", "TELEFONE",
            "DATA CONTRATO", "ESTADO", "EMAIL", "SENHA", "CARGO"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Mfuncionario m : f.pesquisar(pesquisar)) {
            Object[] dado = {m.getId_funcionario(), m.getNome(), m.getGenero(), m.getEspecialidade(), m.getN_bi(), m.getTelefone(),
                m.getData_contrato(), m.getStatu(), m.getEmail(), m.getSenha(), m.getCargo()};
            dt.addRow(dado);
            if (m.getStatu().equalsIgnoreCase("activo")) {
                qtdfuncionario++;
            }
        }
        return qtdfuncionario;
    }

    private void LIMPAR() {
        txtbi.setText("");
        txtemail.setText("");
        txtcontrato.setText("");
        cbcargo.setSelectedIndex(0);
        txtnome.requestFocus();
        txtnome.setText("");
        txtsenha.setText("");
        txttelefone.setText("");
        txtespecialidade.setText("");
        cbestado.setSelectedIndex(0);
        cbgenero.setSelectedIndex(0);
    }
}
